#!/bin/bash
cp ./deb/pool/main/penguins-eggs*amd64.deb ../penguins-eggs-ppa/dists/amd64
cp ./deb/pool/main/penguins-eggs*arm64.deb ../penguins-eggs-ppa/dists/arm64
cp ./deb/pool/main/penguins-eggs*i386.deb ../penguins-eggs-ppa/dists/i386