#!/bin/bash
VER=$1

# Chiede la password in modo sicuro (non la mostra a schermo)
read -sp "Inserisci la password per root@192.168.1.2: " SSH_PASSWORD
echo # Aggiunge una riga vuota per pulizia

# Esporta la password per sshpass
export SSHPASS="$SSH_PASSWORD"

# Esegui i comandi scp usando sshpass con l'opzione -e (legge da variabile d'ambiente)
sshpass -e scp ./alpine/x86_64/packaging/x86_64/penguins-eggs*$VER*r?.apk    root@192.168.1.2:/eggs/alpine/x86_64/
sshpass -e scp ./arch/penguins-eggs*$VER*any.pkg.tar.zst                     root@192.168.1.2:/eggs/aur
sshpass -e scp ./deb/pool/main/penguins-eggs*$VER*amd64.deb                 root@192.168.1.2:/eggs/debs
sshpass -e scp ./deb/pool/main/penguins-eggs*$VER*arm64.deb                  root@192.168.1.2:/eggs/debs
sshpass -e scp ./deb/pool/main/penguins-eggs*$VER*i386.deb                   root@192.168.1.2:/eggs/debs
sshpass -e scp ./manjaro/penguins-eggs-*$VER*-any.pkg.tar.zst                root@192.168.1.2:/eggs/manjaro
sshpass -e scp ./rpm/fedora/42/penguins-eggs-*$VER*-1.fc42.x86_64.rpm        root@192.168.1.2:/eggs/fedora
sshpass -e scp ./rpm/el/9/penguins-eggs-*$VER*-1.el9.x86_64.rpm              root@192.168.1.2:/eggs/el9
sshpass -e scp ./rpm/opensuse/leap/penguins-eggs-*$VER*-1.x86_64.rpm         root@192.168.1.2:/eggs/opensuse

# Pulisce le variabili per sicurezza
unset SSHPASS SSH_PASSWORD

echo "Copia completata!"